import Head from 'next/head'
import Image from 'next/image'
import { Urbanist } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/blocks/header/header'
import Banner from '@/blocks/banner/banner'
import Counter from '@/blocks/counter/counter'

const urbanist = Urbanist({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Nazz Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={urbanist.className}>

        <Header/>
        <Banner/>
        <Counter/>
      </div>
   
    </>
  )
}
