import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <section className='m-5'>
        <div className='container'>
          <div className='row'>
            <div className='col-12'>
              <h1>Hi, Welcome to my profile</h1>
              <p className='text-black'>I will make your Imagination into Real</p>
              
            </div>
          </div>
        </div>

        </section>
      
      </main>
    </>
  )
}
